/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bastion01.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plano002.geometry} material={materials['Material.042']} position={[-0.78, 9.64, -6.35]} rotation={[-0.26, -0.31, -1.96]} />
      <mesh geometry={nodes.Cono.geometry} material={nodes.Cono.material} position={[1.61, 1.47, 0.04]} rotation={[0, 0, -1.6]} scale={[0.3, 0.18, 0.3]} />
      <mesh geometry={nodes.Curva_Bézier.geometry} material={materials['Material.020']} position={[1.32, 0.74, 0.05]} rotation={[Math.PI, 0.02, -1.66]} scale={[0.79, 1, 1]} />
      <mesh geometry={nodes.Cilindro002.geometry} material={materials['Material.031']} position={[1.63, 1.51, 0.05]} rotation={[0, 0, -1.56]} scale={0.2} />
      <mesh geometry={nodes.Cilindro.geometry} material={nodes.Cilindro.material} position={[2.7, 0.63, -0.37]} rotation={[0, 0, -Math.PI / 2]} scale={[0, 0.26, 0]} />
      <mesh geometry={nodes.Esfera001.geometry} material={materials['Material.019']} position={[-1.26, 1.48, -0.1]} scale={0.03} />
      <mesh geometry={nodes.Cubo010.geometry} material={materials['Material.021']} position={[1.39, 0.56, 0.05]} scale={[0.13, 0.69, 0.39]} />
      <mesh geometry={nodes.Cubo009.geometry} material={materials['Material.022']} position={[1.03, 0, 0.05]} scale={[0.97, 0.09, 0.57]} />
      <mesh geometry={nodes.Esfera.geometry} material={materials['Material.018']} position={[0.68, 1.48, 0.05]} scale={0.22} />
      <mesh geometry={nodes.Cubo.geometry} material={materials['Material.010']} position={[0.94, 0.96, 0.05]} rotation={[0, 0, -2.03]} scale={[0.27, 0.01, 0.08]} />
      <mesh geometry={nodes.Torus.geometry} material={materials['Material.007']} position={[1.07, 1.47, 0.05]} rotation={[0, 0, -Math.PI / 2]} scale={0.27} />
      <group position={[0, 0.89, 0.09]} rotation={[3.13, 0, 0]} scale={[2.21, 0.06, 1]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.037']} />
      </group>
      <mesh geometry={nodes.Cubo001.geometry} material={materials['Material.012']} position={[1.17, 1.11, 0.05]} rotation={[0.06, -0.1, -1.09]} scale={[0.12, 0.01, 0.08]} />
      <mesh geometry={nodes.Cubo002.geometry} material={materials['Material.009']} position={[0.94, 1.72, 0.48]} rotation={[-2.12, 0, -2.03]} scale={[0.23, 0.01, 0.07]} />
      <mesh geometry={nodes.Cubo003.geometry} material={materials['Material.015']} position={[1.17, 1.65, 0.36]} rotation={[-2.06, -0.1, -1.09]} scale={[0.12, 0.01, 0.08]} />
      <mesh geometry={nodes.Cubo004.geometry} material={materials['Material.008']} position={[0.93, 1.69, -0.41]} rotation={[1.86, 0, -2.03]} scale={[0.23, 0.01, 0.07]} />
      <mesh geometry={nodes.Cubo005.geometry} material={materials['Material.011']} position={[1.16, 1.65, -0.27]} rotation={[1.91, -0.1, -1.09]} scale={[0.12, 0.01, 0.08]} />
      <mesh geometry={nodes.Cubo006.geometry} material={materials['Material.029']} position={[0.14, 1.9, 0.63]} rotation={[2.57, 0.07, -0.01]} scale={[1, 0.17, 0.06]} />
      <mesh geometry={nodes.Cilindro001.geometry} material={materials['Material.016']} position={[0.43, 1.47, 0.05]} rotation={[1.04, 0, -Math.PI / 2]} scale={[-0.32, -0.63, -0.32]} />
      <mesh geometry={nodes.Cubo007.geometry} material={materials['Material.035']} position={[0.14, 1.84, -0.59]} rotation={[0.5, 0.07, -0.01]} scale={[1, 0.17, 0.06]} />
      <mesh geometry={nodes.Cubo008.geometry} material={materials['Material.038']} position={[0.17, 0.68, 0.04]} rotation={[-1.61, 0.05, -0.05]} scale={[1, 0.17, 0.06]} />
      <mesh geometry={nodes.Esfera002.geometry} material={materials['Material.023']} position={[-1.26, 1.48, 0.19]} scale={0.03} />
      <mesh geometry={nodes.Esfera003.geometry} material={materials['Material.024']} position={[-1.26, 1.62, 0.05]} scale={0.03} />
      <mesh geometry={nodes.Esfera004.geometry} material={materials['Material.025']} position={[-1.26, 1.35, 0.05]} scale={0.03} />
      <mesh geometry={nodes.Esfera005.geometry} material={materials['Material.026']} position={[-1.26, 1.5, 0.05]} scale={0.03} />
      <mesh geometry={nodes.Curva_Bézier001.geometry} material={materials['Material.030']} position={[1.32, 0.74, 0.05]} rotation={[Math.PI, -0.16, -1.66]} scale={[0.79, 1, -1.15]} />
      <mesh geometry={nodes.Cilindro003.geometry} material={nodes.Cilindro003.material} position={[1.59, 1.51, 0.03]} rotation={[0, 0, -1.56]} scale={0.15} />
      <mesh geometry={nodes.Cilindro004.geometry} material={materials['Material.032']} position={[1.61, 1.51, -0.04]} rotation={[-0.01, 0.25, -1.5]} scale={0.2} />
      <group position={[-2.74, 1.48, 0.05]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.32, -0.22, -0.32]}>
        <mesh geometry={nodes.Cilindro007.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cilindro007_1.geometry} material={materials['Material.041']} />
      </group>
      <mesh geometry={nodes.Cubo011.geometry} material={materials['Material.013']} position={[-0.91, 1.75, 0.47]} rotation={[1.06, 0, 0]} scale={[0.02, 0.13, 0.03]} />
      <group position={[0, 1.67, -0.47]} rotation={[-1.06, 0, 0]} scale={[2.21, 0.06, 1]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.043']} />
      </group>
      <group position={[0, 1.76, 0.5]} rotation={[1.04, 0, 0]} scale={[2.21, 0.06, 1]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.044']} />
      </group>
      <mesh geometry={nodes.Esfera006.geometry} material={materials['Material.045']} position={[-5.1, 1.5, 0.03]} scale={[2.44, 0.02, 0.02]} />
      <mesh geometry={nodes.Esfera007.geometry} material={materials['Material.046']} position={[-5.85, 1.5, 0.03]} scale={[2.54, 0.1, 0.1]} />
    </group>
  )
}

useGLTF.preload('/Bastion01.gltf')
