/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Columbisdos(props) {
  const { nodes, materials } = useGLTF('/COLUMBIS2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.47, 9.57, -1.03]} scale={[1, 1, -0.82]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/COLUMBIS2.gltf')
