/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Namikijs(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Namikijs.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NAMIKI" position={[0, 0.13, 0]} rotation={[0, 0.01, 0]} scale={0.2}>
          <primitive object={nodes.Bone004} />
          <skinnedMesh name="I_dedo_medio000" geometry={nodes.I_dedo_medio000.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio000.skeleton} />
          <skinnedMesh name="I_dedo_medio001" geometry={nodes.I_dedo_medio001.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio001.skeleton} />
          <skinnedMesh name="I_dedo_medio002" geometry={nodes.I_dedo_medio002.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio002.skeleton} />
          <skinnedMesh name="I_dedo_medio003" geometry={nodes.I_dedo_medio003.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio003.skeleton} />
          <skinnedMesh name="I_dedo_medio004" geometry={nodes.I_dedo_medio004.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio004.skeleton} />
          <skinnedMesh name="I_dedo_medio005" geometry={nodes.I_dedo_medio005.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio005.skeleton} />
          <skinnedMesh name="I_dedo_medio006" geometry={nodes.I_dedo_medio006.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio006.skeleton} />
          <skinnedMesh name="I_dedo_medio007" geometry={nodes.I_dedo_medio007.geometry} material={materials.pecho} skeleton={nodes.I_dedo_medio007.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Namikijs.gltf')
