/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Voyagerr(props) {
  const { nodes, materials } = useGLTF('/Voyagerr.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cubo006.geometry} material={nodes.Cubo006.material} position={[-114.71, 35.02, -21.26]} rotation={[0, 1.47, 0]} scale={[11.86, 1.19, 11.86]} />
      <mesh geometry={nodes.Cilindro040.geometry} material={nodes.Cilindro040.material} position={[-174.42, -19.74, -16.12]} rotation={[Math.PI / 2, 0, 0]} scale={3.86} />
      <mesh geometry={nodes.Cilindro039.geometry} material={nodes.Cilindro039.material} position={[-165.7, -6.73, -16.23]} rotation={[Math.PI / 2, 0, 0]} scale={3.27} />
      <mesh geometry={nodes.Cilindro037.geometry} material={nodes.Cilindro037.material} position={[153.32, -31.05, 172.32]} rotation={[0, -1.04, -Math.PI / 2]} scale={[0.28, 115.53, 0.27]} />
      <mesh geometry={nodes.Cilindro032.geometry} material={nodes.Cilindro032.material} position={[131.27, -2.2, 28.08]} rotation={[-0.03, -0.21, -2.15]} scale={[0.81, 20.17, 0.95]} />
      <mesh geometry={nodes.Cubo005.geometry} material={nodes.Cubo005.material} position={[-54.8, -83.22, -9.2]} rotation={[0, -0.2, -0.58]} scale={[-1.63, 18.67, 19.56]} />
      <mesh geometry={nodes.Cilindro028.geometry} material={nodes.Cilindro028.material} position={[74.3, -75.62, 88.34]} rotation={[-0.32, 0, -0.51]} scale={[3.95, 32.79, 3.95]} />
      <mesh geometry={nodes.Cilindro013.geometry} material={nodes.Cilindro013.material} position={[19.37, -7.47, -69.62]} rotation={[0.39, 0.04, -0.92]} scale={[1.17, 12.43, 1.17]} />
      <mesh geometry={nodes.Cilindro012.geometry} material={nodes.Cilindro012.material} position={[-202.84, -32.16, -27.03]} rotation={[Math.PI / 2, 0, 0]} scale={[11.3, 15.94, 11.3]} />
      <mesh geometry={nodes.Cubo004.geometry} material={nodes.Cubo004.material} position={[-205.57, -15.69, -26.29]} scale={11.3} />
      <mesh geometry={nodes.Cubo003.geometry} material={nodes.Cubo003.material} position={[-171.25, -12.67, -22.95]} scale={[-14.5, -16.28, -9.21]} />
      <mesh geometry={nodes.Cilindro010.geometry} material={nodes.Cilindro010.material} position={[-188.8, 13.99, -23.01]} scale={[3.55, 19.82, 3.55]} />
      <mesh geometry={nodes.Cubo001.geometry} material={nodes.Cubo001.material} position={[128.7, 18.62, 29.49]} rotation={[-1.09, 0.95, 1.08]} scale={[5.84, 5.84, 23.29]} />
      <mesh geometry={nodes.Cilindro004.geometry} material={nodes.Cilindro004.material} position={[-40.69, 8.04, -26.62]} rotation={[0.48, 0.2, 0.32]} scale={[1.08, 30.42, 1.29]} />
      <mesh geometry={nodes.Cubo.geometry} material={nodes.Cubo.material} position={[-167.92, 23.77, -19.98]} rotation={[0, -0.16, 0]} scale={[13.49, 11.3, 11.36]} />
      <mesh geometry={nodes.Cono001.geometry} material={nodes.Cono001.material} position={[43.99, 106.84, -2.01]} scale={[6.73, 4.62, 6.73]} />
      <mesh geometry={nodes.Cilindro.geometry} material={nodes.Cilindro.material} position={[43.39, 22.99, 2.58]} scale={[71.15, 11.11, 71.15]} />
      <mesh geometry={nodes.Cono.geometry} material={nodes.Cono.material} position={[43.39, 31.55, 2.58]} rotation={[0, 0, 3.14]} scale={[118.83, 30.95, 118.82]} />
      <mesh geometry={nodes.Cilindro001.geometry} material={nodes.Cilindro001.material} position={[43.92, 40.83, -2.5]} scale={[9.01, 5.81, 9.01]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[44.73, -36.39, 83.94]} rotation={[Math.PI / 2, 0, 0]} scale={[31.64, 12.89, 21.29]} />
      <mesh geometry={nodes.Esfera.geometry} material={nodes.Esfera.material} position={[44.04, 110.46, -2.33]} scale={[15.67, 8.91, 15.67]} />
      <mesh geometry={nodes.Cilindro002.geometry} material={nodes.Cilindro002.material} position={[51.5, 69.17, 15.98]} rotation={[-2.9, 1, 2.7]} scale={[0.79, 38.94, 0.79]} />
      <mesh geometry={nodes.Cilindro003.geometry} material={nodes.Cilindro003.material} position={[-37.61, 14.47, -2.19]} rotation={[0, 0.23, -Math.PI / 2]} scale={[-0.7, -17.77, -0.68]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[45.01, 8.77, 66.36]} rotation={[Math.PI / 2, 0, 0]} scale={[25.24, 10.16, 9.79]} />
      <mesh geometry={nodes.Cilindro005.geometry} material={nodes.Cilindro005.material} position={[-44.69, 8.25, 18.46]} rotation={[-0.65, 0.2, 0.32]} scale={[1.08, 30.42, 1.29]} />
      <mesh geometry={nodes.Cilindro006.geometry} material={nodes.Cilindro006.material} position={[-40.69, 0.23, -7.65]} rotation={[-0.17, 0.21, -0.01]} scale={[0.75, 15.35, 0.9]} />
      <mesh geometry={nodes.Cilindro007.geometry} material={nodes.Cilindro007.material} position={[-40.69, 0.23, 0.78]} rotation={[0.25, 0.21, -0.01]} scale={[0.75, 15.35, 0.9]} />
      <mesh geometry={nodes.Cilindro008.geometry} material={nodes.Cilindro008.material} position={[-67.22, -10.89, -8.94]} rotation={[0.26, -0.24, 1.11]} scale={[1.08, 30.42, 1.29]} />
      <mesh geometry={nodes.Cubo002.geometry} material={nodes.Cubo002.material} position={[124.12, 11.97, 30.32]} rotation={[-1.09, 0.95, 1.08]} scale={0.66} />
      <mesh geometry={nodes.Cilindro009.geometry} material={nodes.Cilindro009.material} position={[-164.56, -5, -28.49]} rotation={[Math.PI / 2, 0, 0]} scale={3.58} />
      <mesh geometry={nodes.Cilindro011.geometry} material={nodes.Cilindro011.material} position={[-165.75, -20.12, -27.05]} rotation={[Math.PI / 2, 0, 0]} scale={5.37} />
      <mesh geometry={nodes.Cilindro014.geometry} material={nodes.Cilindro014.material} position={[-164.56, -5, -23.18]} rotation={[Math.PI / 2, 0, 0]} scale={3.58} />
      <mesh geometry={nodes.Cilindro015.geometry} material={nodes.Cilindro015.material} position={[68.68, -6.38, -67.33]} rotation={[0.5, -0.65, -0.58]} scale={[1.17, 12.43, 1.17]} />
      <mesh geometry={nodes.Cilindro016.geometry} material={nodes.Cilindro016.material} position={[108.09, -6.34, -33.01]} rotation={[0.89, -0.77, 0.02]} scale={[1.17, 12.43, 1.17]} />
      <mesh geometry={nodes.Cilindro017.geometry} material={nodes.Cilindro017.material} position={[114.56, -6.34, 22.59]} rotation={[0.87, -0.16, 0.45]} scale={[1.17, 12.43, 1.17]} />
      <mesh geometry={nodes.Cilindro018.geometry} material={nodes.Cilindro018.material} position={[91.29, -6.34, 62.55]} rotation={[0.23, -0.07, 0.87]} scale={[1.17, 12.43, 1.17]} />
      <mesh geometry={nodes.Cilindro019.geometry} material={nodes.Cilindro019.material} position={[43.05, -6.34, 78.43]} rotation={[-0.42, -0.07, 0.87]} scale={[1.17, 12.43, 1.17]} />
      <mesh geometry={nodes.Cilindro020.geometry} material={nodes.Cilindro020.material} position={[-7.43, -6.34, 57.57]} rotation={[-0.9, 0.26, 0.36]} scale={[1.17, 12.43, 1.17]} />
      <mesh geometry={nodes.Cilindro027.geometry} material={nodes.Cilindro027.material} position={[105.93, -9.24, 43.42]} rotation={[-0.98, 1.12, -3.12]} scale={[-1.15, -12.23, -1.15]} />
      <mesh geometry={nodes.Cilindro026.geometry} material={nodes.Cilindro026.material} position={[114.5, -8.24, -4.37]} rotation={[-2.44, 0.97, -1.49]} scale={[-1.15, -12.23, -1.15]} />
      <mesh geometry={nodes.Cilindro025.geometry} material={nodes.Cilindro025.material} position={[98.2, -7.47, -49.65]} rotation={[-2.38, 0.66, -1.19]} scale={[-1.15, -12.23, -1.15]} />
      <mesh geometry={nodes.Cilindro024.geometry} material={nodes.Cilindro024.material} position={[38.27, -6.11, -73.08]} rotation={[-0.39, 0.98, -1.82]} scale={[-1.56, -14.2, -1.19]} />
      <mesh geometry={nodes.Cilindro023.geometry} material={nodes.Cilindro023.material} position={[-5.12, -5.06, -54.34]} rotation={[-0.96, 1.32, -1.35]} scale={[-1.15, -12.23, -1.15]} />
      <mesh geometry={nodes.Cilindro022.geometry} material={nodes.Cilindro022.material} position={[-30.85, -4.53, -11.53]} rotation={[1.28, 1.1, 2.79]} scale={[-1.15, -12.23, -1.15]} />
      <mesh geometry={nodes.Cilindro021.geometry} material={nodes.Cilindro021.material} position={[-21.64, -4.91, 40.53]} rotation={[1.11, 0.54, 2.37]} scale={[-1.15, -12.23, -1.15]} />
      <mesh geometry={nodes.Cilindro029.geometry} material={nodes.Cilindro029.material} position={[74.3, -75.62, -79.79]} rotation={[0.34, 0, -0.51]} scale={[3.95, 32.79, 3.95]} />
      <mesh geometry={nodes.Cilindro031.geometry} material={nodes.Cilindro031.material} position={[-41.72, -75.62, 20.73]} rotation={[-2.01, -1.22, -2.54]} scale={[3.95, 32.79, 3.95]} />
      <mesh geometry={nodes.Cilindro030.geometry} material={nodes.Cilindro030.material} position={[127.52, -75.62, 30.21]} rotation={[1.39, -1.22, 0.88]} scale={[3.95, 32.79, 3.95]} />
      <mesh geometry={nodes.Cubo007.geometry} material={nodes.Cubo007.material} position={[232.58, -20.54, 55.72]} rotation={[0, -0.25, -1.63]} scale={[10.85, 16.44, 10.85]} />
      <mesh geometry={nodes.Cilindro033.geometry} material={nodes.Cilindro033.material} position={[132.74, -35.03, 22.68]} rotation={[-0.36, -0.49, -1.21]} scale={[0.81, 20.17, 0.95]} />
      <mesh geometry={nodes.Cilindro034.geometry} material={nodes.Cilindro034.material} position={[210.49, -37.84, 37.75]} rotation={[0.51, 0.02, -0.65]} scale={[0.63, 15.51, 0.73]} />
      <mesh geometry={nodes.Cilindro035.geometry} material={nodes.Cilindro035.material} position={[132.74, -35.03, 42.53]} rotation={[-0.32, -0.13, -1.09]} scale={[0.81, 20.17, 0.95]} />
      <mesh geometry={nodes.Cilindro036.geometry} material={nodes.Cilindro036.material} position={[176.13, -42.7, 36.58]} rotation={[0.24, -0.55, -0.1]} scale={[0.53, 25.38, 0.61]} />
      <mesh geometry={nodes.Cilindro038.geometry} material={nodes.Cilindro038.material} position={[164.27, -31.05, 135.03]} rotation={[0, -0.77, -Math.PI / 2]} scale={[0.28, 115.53, 0.27]} />
    </group>
  )
}

useGLTF.preload('/Voyagerr.gltf')
